version: '3'
services:
  web:
    image: sbprjnonroot:latest
    environment:
      TZ: Europe/Zurich
      spring.config.location: /app/parms/
      spring.config.name: somevalue

    ports:
      - "8080:8080"
    volumes:
      - /Users/elmos/OneDrive/TECH/github/springb-nginx-docker/parms:/app/parms:ro
      - /Users/elmos/OneDrive/TECH/github/springb-nginx-docker/logs:/app/logs:rw
